### PR TITLE
Get rid of the notion of “person”

### PR DESCRIPTION
**Pull request by Niols**
As previously discussed, the notion of person is a bit broken and the database is not filled properly. I think it is best to remove it, and potentially to reintroduce it later under a different form. WDYT @R1kM?

### CODE REVIEW

**Comment by Niols** [comment]
I would think as a second plan that we could rename the current notion of “credit” into “person” to align on the SCDDB. We would keep the name “credit” for different data-types such as the notion of credit in MusicBrainz.

**Comment by R1kM** [comment]
Thinking more about it, I have mixed feelings about this. While I agree it is currently a bit of a hassle (and the db consistency isn't great), I like that finding different credits a person is involved in is currently easy.
However, I won't fight strongly for it; the PR looks good, and I'm happy to see it merged.

**Comment by Niols** [comment]
> I like that finding different credits a person is involved in is currently easy.

I agree with this in principle. But the database is very inconsistent there so it doesn't actually work that well, and I personally never use it for this reason. That's why I would think a plan more like:

- We remove the current notion of Person.
- We rename the current notion of Credit into a Person (aligning ourselves with the SCDDB on the terminology there).
- We add a new notion of Credit that handles complex credit, inspired by that of MusicBrainz (which, in particular, would not be a new model but just a fancy type used wherever there is a credit now).

would have a much better chance of success. If you're still not convinced, I'd happily discuss this more or even drop the change.

**Comment by R1kM** [comment]
Yeah, that sounds reasonable, and would probably help with #54 as well.
Merging, thanks!

**Pull request merged**
