### PR TITLE
Split the router into per-model endpoints - !85

### PR DESCRIPTION
**Pull request by Niols**
https://gitlab.vlanvin.fr/paris-band/dancelor/-/merge_requests/85

_should be reviewed and merged after #176_

### CODE REVIEW

**Comment by Niols** [comment]
In GitLab by @Niols on Jan 6, 2023, 15:10

added 2 commits

<ul><li>1fdaeeed - Factorise victor levels</li><li>03f40184 - Regroup stuff</li></ul>

[Compare with previous version](/paris-band/dancelor/-/merge_requests/85/diffs?diff_id=596&start_sha=12a9c248dd1d8acb77906bb5dd6062d07847dd46)

**Comment by Niols** [comment]
In GitLab by @Niols on Jan 6, 2023, 15:41

added 2 commits

<ul><li>57e96e25 - Support prefixes in Madge&#39;s router</li><li>f3217242 - Factorise prefixes in `ApiRouter`</li></ul>

[Compare with previous version](/paris-band/dancelor/-/merge_requests/85/diffs?diff_id=598&start_sha=03f40184c6b0b62c4bf2cc0e16d66bc7e3e48485)

**Comment by Niols** [comment]
In GitLab by @Niols on Apr 25, 2023, 16:54

removed review request for @R1kM

**Comment by Niols** [comment]
In GitLab by @Niols on Apr 25, 2023, 16:54

unassigned @Niols

**Comment by Niols** [comment]
@R1kM I think this PR isn't hard to review in the context of #176: it only splits the API routes so that the endpoints are defined close to the models and not all in the same space. Any chance we could merge it?

**Comment by R1kM** [comment]
This looks good to me. Feel free to merge.

**Pull request merged**
